name: directory_tree
description: Deterministic directory tree builder for Dart.
version: 1.0.0
homepage: https://github.com/omar-hanafy/directory_tree
repository: https://github.com/omar-hanafy/directory_tree
issue_tracker: https://github.com/omar-hanafy/directory_tree/issues
documentation: https://github.com/omar-hanafy/directory_tree#readme
example: example

topics:
  - filesystem
  - tree

environment:
  sdk: ^3.10.4

dependencies:
  equatable: ^2.0.7
  path: ^1.9.1
  uuid: ^4.5.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
